name: Compile Kivy Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Compilazione con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer -v android debug

      - name: Carica APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: ${{ steps.buildozer.outputs.filename }}
